[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.2.1"
dotenv = "0.15.0"
serde = "1.0.151"
futures = "0.3.25"

[dependencies.mongodb]
version = "2.2.0"
default-features = false
features = ["async-std-runtime"]
